# Generated by Django 3.1.6 on 2021-02-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_title', models.CharField(max_length=200, verbose_name='Название')),
                ('en_title', models.CharField(max_length=200, verbose_name='Оригинальное Название')),
                ('product_year', models.PositiveSmallIntegerField(default=2020, verbose_name='Год')),
                ('slug', models.SlugField(max_length=100)),
                ('country', models.CharField(max_length=50, verbose_name='Старна')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['ru_title'],
            },
        ),
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_title', models.CharField(max_length=200, verbose_name='Название')),
                ('en_title', models.CharField(max_length=200, verbose_name='Оригинальное Название')),
                ('product_year', models.PositiveSmallIntegerField(default=2020, verbose_name='Год')),
                ('slug', models.SlugField(max_length=100)),
                ('country', models.CharField(max_length=50, verbose_name='Старна')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('number_of_episodes', models.PositiveSmallIntegerField(verbose_name='Кол-во серий')),
                ('season_number', models.PositiveSmallIntegerField(verbose_name='Номер сезона')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
